modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/Extra-Potions/issues"

[[mods]]
    modId="extrapotions"
    version="${file.jarVersion}"
    displayName="Extra Potions"
    displayURL="https://github.com/CAS-ual-TY/Extra-Potions"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team."
    authors="CAS_ual_TY"
    description="Makes almost all Minecraft effects available for brewing and adds new high-risk high-reward trade-off potions."
