modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CAS-ual-TY/Extra-Potions/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/CAS-ual-TY/Extra-Potions"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="${mod_authors}"
    displayTest="MATCH_VERSION"
    description='''${mod_description}'''